spring:
  application:
    name: demo
  
  jms:
    listener:
      auto-startup: true
      acknowledge-mode: auto
      concurrency: 1

ibm:
  mq:
    queue-manager: QM1
    channel: DEV.APP.SVRCONN
    conn-name: localhost(1414)
    user: app
    password: passw0rd
    
# Application specific configuration
mq:
  queue-name: DEV.QUEUE.1